### ISSUE TITLE
[Feature request] winning screen

### ISSUE THREAD

**Issue by MariusMeiners** [irhadkul/NodeConnect4#1]
priority: high
type: feature request
due version: 1.0.0

Can you please show a fullscreen picture of my beautiful face when a player wins with the message "one day you might be as great as me".
Thanks.

best regards 
Marius

**Comment by irhadkul** [comment]
Hi Marius,

I understand your concerns and I can promise that I will be working hard to implement your feature. 😎 

P.S. you are also allowed to commit

Regards,
Irhad
